module_name=delegate_operation_replacer

ccflags-y :=  -I$(src)/.. -I$(src) -I$(src)/../../../../

obj-m := $(module_name).o
$(module_name)-y := delegate_operation_replacer_module.o operation_replacer.o data_map.o