module_name=delegate_base_update_replacement

ccflags-y :=  -DUPDATE_REPLACEMENT -I$(src)/.. -I$(src)/../delegate_operation_replacer/ -I$(src)/../../../..

obj-m := $(module_name).o
$(module_name)-y := base_module.o