#ifndef MIST_PARSER_HH
#define MIST_PARSER_HH

#include "mist_parser_base.tab.hh"
#include "mist_scanner.hh"
#include "mist_ast.hh"

#include <iostream>

class MistParser
{
public:
	MistParser();
	
	/* 
     * Parse given stream and build given ast according to it.
     * 
     * If non-empty, 'filename' is used in error-reporting.
     */
	void parse(std::istream& stream, MistAST& ast, const std::string& filename = "");
/* 
 * Next fields are implementation specific, and used only by
 * yy::parser, generated by bison.
 */
	MistScanner scanner;
	yy::parser parserBase;
    /* These field are set only while parsing. */
    std::string filename;
    MistAST* ast;
};

#endif /* MIST_PARSER_HH */